// Re-export shim: repo has moved to inventory/repo.js
export {
  listItems,
  listItemBarcodes,
  listItemBarcodesSince,
  applyScanEventByBarcode,
  applyScanEventByBarcodeChosenItem,
  getItemByBarcodeExact,
  getItemsByBarcodeExact,
  incrementItemQuantity,
  attachBarcodeToItem,
  detachBarcodeFromItem,
  getItem,
  createItem,
  updateItem,
  softDeleteItem,
  listCategories,
  createCategory,
  updateCategory,
  deleteCategory,
  listLocations,
  createLocation,
  updateLocation,
  deleteLocation,
  upsertManyByIdLww,
  exportSnapshot,
  importSnapshotLww,
  appendSyncLog,
  listSyncLog
} from './inventory/repo.js';
